jobs:
  - type: snap
    name: "my_job"
    filesystems: {
      "<": true,
    }
    snapshotting:
      type: manual
    pruning:
      keep:
        - type: last_n
          count: 10

include:
  - ./included.yml
